name: sqlliteprototype
description: A Flutter user registration application with SQLite database.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.9.3
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
